spring:
  profiles:
    active: technifutur

---
spring:
  application:
    name: market-service
  config:
    import: configserver:http://user:pass@localhost:9999
    activate:
      on-profile: default


---
spring:
  application:
    name: market-service
  config:
    import: configserver:http://user:pass@10.27.1.17:9999
    activate:
      on-profile: technifutur