spring:
  profiles:
    active: default

---
spring:
  application:
    name: market-service
  config:
    import: configserver:http://user:pass@localhost:9999
    activate:
      on-profile: default
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


---
spring:
  application:
    name: market-service
  config:
    import: configserver:http://user:pass@10.27.1.17:9999
    activate:
      on-profile: technifutur
  rabbitmq:
    port: 5672
    host: 10.27.1.17
    username: guest
    password: guest