server:
  port: 8484
spring:
  application:
    name: order-service
  config:
    import: configserver:http://user:pass@localhost:9999
  datasource:
    url: jdbc:h2:mem:online_order_db
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true