spring:
  application:
    name: user-service
  profiles:
    active: default
  config:
    import: configserver:http://user:pass@localhost:9999
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
