spring:
  application:
    name: game-service
  profiles:
    active: default
#    alterner entre technifutur et default (pour la maison)
  config:
    import: configserver:http://user:pass@localhost:9999
#    alterner entre 10.27.1.17 et localhost
  feign:
    client:
      config:
        default:
          - connectTimeout: 160000000
          - readTimeout: 160000000
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest