spring:
  application:
    name: game-service
  datasource:
    url: jdbc:h2:mem:tp4DB
    username: user
    password: pswd
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  config:
    import: configserver:http://user:pass@localhost:9999

server:
  port: 8282