spring:
  application:
    name: game-service
  profiles:
    active: technifutur
#    alterner entre technifutur et default (pour la maison)
  config:
    import: configserver:http://user:pass@10.27.1.17:9999
#    alterner entre 10.27.1.17 et localhost