server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/LionelD29/tp4-mist-config-server.git
          clone-on-start: true
          default-label: main
  security:
    user:
      name: user
      password: pass